INSERT INTO item (name, details, type, level, change_date) VALUES ('Netlify', 'You can create static website content, check it into GitHub and then quickly and easily get your site live and available.', 'Platform', 'Assess', '2018-11-11 11:11:11.000')
INSERT INTO item (name, details, type, level, change_date) VALUES ('Corda', 'Corda is a distributed ledger technology (DLT) platform focused on the financial field.', 'Platform', 'Assess', '2018-10-11 12:10:11.000')
INSERT INTO item (name, details, type, level, change_date) VALUES ('Keycloak', 'Keycloak is an open source identity and access management solution that makes it easy to secure applications or microservices with little to no code.', 'Platform', 'Trial', '2017-10-11 12:10:00.000')
INSERT INTO item (name, details, type, level, change_date) VALUES ('Andie', '-', 'Platform', 'Hold', '2017-10-11 13:10:00.000')
INSERT INTO level(name, details, order_number) VALUES ('Adopt', 'We feel strongly that the industy should be adopting these items. We use them when appropriate on our projects.', 1)
INSERT INTO level(name, details, order_number) VALUES ('Trial', 'Worth pusuing. It is important to understand how to build up this capability. Enterprises should try this technology on a project that can handle the risk.', 2)
INSERT INTO level(name, details, order_number) VALUES ('Access', 'Worth exploring with the goal of understanding how it will afect your enterprise.', 3)
INSERT INTO level(name, details, order_number) VALUES ('Hold', 'Process with caution.', 4)
INSERT INTO category(name, details, order_number) VALUES ('Techniques', '-', 1)
INSERT INTO category(name, details, order_number) VALUES ('Tools', '-', 2)
INSERT INTO category(name, details, order_number) VALUES ('Platform', '-', 3)
INSERT INTO category(name, details, order_number) VALUES ('Languages & frameworks', '-', 4)
INSERT INTO car(make, model, price) VALUES('Toyota', 'Celica',35000)
INSERT INTO car(make, model, price) VALUES('Ford', 'Mondeo',32000)
INSERT INTO car(make, model, price) VALUES('Porsche', 'Boxter',72000)
INSERT INTO car(make, model, price) VALUES('Peugeot', '307',21000)
INSERT INTO car(make, model, price) VALUES('Volkswagen', 'Golf',23000)
INSERT INTO car(make, model, price) VALUES('Audi', 'Quatro',69000)
INSERT INTO car(make, model, price) VALUES('BMW', 'i8',135000)
INSERT INTO car(make, model, price) VALUES('Kia', 'Rio',16000)
INSERT INTO car(make, model, price) VALUES('Audi', 'A3',32000)
INSERT INTO car(make, model, price) VALUES('BMW', 'i3',48000)
INSERT INTO product(name, description, price) VALUES('phone', 'Samsung Galaxy A3 2017', 7000)
INSERT INTO product(name, description, price) VALUES('3D printer', 'Snapmaker', 12000)
INSERT INTO product(name, description, price) VALUES('camera', 'Canon G9X', 9000)
INSERT INTO product(name, description, price) VALUES('CPU', 'Intel Core i7-8700', 8400)
INSERT INTO hero(name) VALUES('Isis')
INSERT INTO hero(name) VALUES('Ra')
INSERT INTO hero(name) VALUES('Horus')
INSERT INTO hero(name) VALUES('Osiris')
INSERT INTO hero(name) VALUES('Bast')
INSERT INTO hero(name) VALUES('Artemis')
INSERT INTO hero(name) VALUES('Freyja')
INSERT INTO hero(name) VALUES('Skadi')
INSERT INTO hero(name) VALUES('Tyr')